# Generated by Django 6.0.7 on 2026-07-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifybag_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('nafdac_number', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
