# Generated by Django 6.0.7 on 2026-07-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifybag_app', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pharmacy_license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pharmacy_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
