# Generated by Django 6.0.7 on 2026-07-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifybag_app', '0006_rename_is_approved_userprofile_is_pharmacy_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pharmacy_license',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
