# Generated by Django 6.0.7 on 2026-07-19 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifybag_app', '0007_userprofile_pharmacy_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveddrug',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='approveddrug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approveddrug',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='approveddrug',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approveddrug',
            name='strength',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
