# Generated by Django 6.0.7 on 2026-07-22 07:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifybag_app', '0008_approveddrug_batch_number_approveddrug_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugverification',
            name='drug_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='drug_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
